import { TransactionCategory } from "types/Transaction";

export const transactionCategoryNameMap: Record<TransactionCategory, string> = {
  [TransactionCategory.Car]: "Car",
  [TransactionCategory.Charity]: "Charity",
  [TransactionCategory.Childcare]: "Childcare",
  [TransactionCategory.Education]: "Education",
  [TransactionCategory.Entertainment]: "Entertainment",
  [TransactionCategory.Food]: "Food",
  [TransactionCategory.Gas]: "Gas",
  [TransactionCategory.Gifts]: "Gifts",
  [TransactionCategory.Groceries]: "Groceries",
  [TransactionCategory.HealthAndFitness]: "Health & Fitness",
  [TransactionCategory.Hobbies]: "Hobbies",
  [TransactionCategory.HomeImprovement]: "Home Improvement",
  [TransactionCategory.Housing]: "Housing",
  [TransactionCategory.Insurance]: "Insurance",
  [TransactionCategory.Internet]: "Internet",
  [TransactionCategory.PersonalCare]: "Personal Care",
  [TransactionCategory.Pets]: "Pets",
  [TransactionCategory.Phone]: "Phone",
  [TransactionCategory.Salary]: "Salary",
  [TransactionCategory.Subscriptions]: "Subscriptions",
  [TransactionCategory.Transit]: "Transit",
  [TransactionCategory.Transfer]: "Transfer",
  [TransactionCategory.Travel]: "Travel",
  [TransactionCategory.Utilities]: "Utilities",
  [TransactionCategory.WorkExpenses]: "Work Expenses",
  [TransactionCategory.Other]: "Other",
};
