export const TRANSACTION_CATEGORIES = [
  "Food",
  "Groceries",
  "Transit",
  "Housing",
  "Utilities",
  "Insurance",
  "Health & Fitness",
  "Debt Repayment",
  "Dining Out",
  "Entertainment",
  "Shopping",
  "Personal Care",
  "Subscriptions",
  "Savings",
  "Investments",
  "Education",
  "Childcare",
  "Gifts & Donations",
  "Travel",
  "Pets",
  "Emergency Fund",
  "Hobbies",
  "Work Expenses",
  "Events",
  "Other",
];
