import {
  faArrowAltCircleLeft,
  faArrowRightRotate,
  faArrowsLeftRight,
  faBriefcase,
  faBus,
  faCalendarDays,
  faCameraRetro,
  faCar,
  faCartShopping,
  faChild,
  faClipboardCheck,
  faFaucetDrip,
  faGasPump,
  faGift,
  faHandHoldingHand,
  faHandHoldingHeart,
  faHouse,
  faMoneyCheckDollar,
  faNotesMedical,
  faPaw,
  faPhone,
  faPlane,
  faQuestion,
  faSchool,
  faScrewdriverWrench,
  faTicket,
  faUtensils,
  faWifi,
} from "@fortawesome/free-solid-svg-icons";
import { TransactionCategory } from "types/Transaction";

export const transactionCategoryImageMap = {
  [TransactionCategory.Car]: faCar,
  [TransactionCategory.Charity]: faHandHoldingHeart,
  [TransactionCategory.Childcare]: faChild,
  [TransactionCategory.Education]: faSchool,
  [TransactionCategory.Entertainment]: faTicket,
  [TransactionCategory.Food]: faUtensils,
  [TransactionCategory.Gas]: faGasPump,
  [TransactionCategory.Gifts]: faGift,
  [TransactionCategory.Groceries]: faCartShopping,
  [TransactionCategory.HealthAndFitness]: faNotesMedical,
  [TransactionCategory.Hobbies]: faCameraRetro,
  [TransactionCategory.HomeImprovement]: faScrewdriverWrench,
  [TransactionCategory.Housing]: faHouse,
  [TransactionCategory.Insurance]: faClipboardCheck,
  [TransactionCategory.Internet]: faWifi,
  [TransactionCategory.PersonalCare]: faHandHoldingHand,
  [TransactionCategory.Pets]: faPaw,
  [TransactionCategory.Phone]: faPhone,
  [TransactionCategory.Salary]: faMoneyCheckDollar,
  [TransactionCategory.Subscriptions]: faCalendarDays,
  [TransactionCategory.Transit]: faBus,
  [TransactionCategory.Travel]: faPlane,
  [TransactionCategory.Transfer]: faArrowsLeftRight,
  [TransactionCategory.Utilities]: faFaucetDrip,
  [TransactionCategory.WorkExpenses]: faBriefcase,
  [TransactionCategory.Other]: faQuestion,
};
